# Generated by Django 4.2.26 on 2025-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': [('ver_aluno', 'Pode visualizar alunos'), ('criar_aluno', 'Pode criar alunos'), ('editar_aluno', 'Pode editar alunos'), ('deletar_aluno', 'Pode deletar alunos')]},
        ),
    ]
