# Generated by Django 4.2.26 on 2025-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'permissions': [('ver_inscricao', 'Pode visualizar inscrições'), ('criar_inscricao', 'Pode criar inscrições'), ('cancelar_inscricao', 'Pode cancelar inscrições')]},
        ),
    ]
