# Generated by Django 4.2.26 on 2025-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'permissions': [('ver_curso', 'Pode visualizar cursos'), ('criar_curso', 'Pode criar cursos'), ('editar_curso', 'Pode editar cursos'), ('deletar_curso', 'Pode deletar cursos')]},
        ),
    ]
