# Generated by Django 6.0.3 on 2026-05-09 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_criar_curso', models.BooleanField(default=False)),
                ('pode_editar_aluno', models.BooleanField(default=False)),
                ('pode_deletar_postagem', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('criar_curso', 'Pode criar curso'), ('editar_aluno', 'Pode editar aluno'), ('deletar_postagem', 'Pode deletar postagem')],
            },
        ),
    ]
