# Generated by Django 4.2.26 on 2025-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'permissions': [('ver_aula', 'Pode visualizar aulas'), ('criar_aula', 'Pode criar aulas'), ('editar_aula', 'Pode editar aulas'), ('deletar_aula', 'Pode deletar aulas')]},
        ),
    ]
