# Generated by Django 4.2.18 on 2025-12-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_alter_modulo_options'),
        ('aulas', '0002_alter_aula_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='curso',
        ),
        migrations.AddField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='modulos.modulo'),
            preserve_default=False,
        ),
    ]
