# Generated by Django 4.2.26 on 2025-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'permissions': [('ver_modulo', 'Pode visualizar módulos'), ('criar_modulo', 'Pode criar módulos'), ('editar_modulo', 'Pode editar módulos'), ('deletar_modulo', 'Pode deletar módulos')]},
        ),
    ]
